server:
  port: 8086

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: ms-ventas-service
          uri: lb://ms-vestas-service
          predicates:
            - Path=/venta/**